# Generated by Django 5.1.1 on 2024-10-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('completed', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Todo list',
                'verbose_name_plural': 'Todo list',
            },
        ),
    ]
